from __future__ import annotations

SECONDS_PER_MINUTE = 60
SECONDS_PER_HOUR = 3600
SECONDS_PER_2H = 2 * SECONDS_PER_HOUR

DEFAULT_TIMEFRAME = "2h"

RSI_PERIOD = 14
RSI_OVERBOUGHT = 70.0
RSI_OVERSOLD = 30.0

ACTIVE_TIER = "ACTIVE"
REST_TIER = "REST"

STATE_NEUTRAL = "NEUTRAL"
STATE_OVERBOUGHT = "OVERBOUGHT"
STATE_OVERSOLD = "OVERSOLD"
